import random

generated_number = random.randint(1, 100)
guess_limit = 5

while True:
    guess = int(input("Please enter your guess: "))

    if guess == generated_number:
        print("Congratulations! You won.")
        break
    elif guess > generated_number:
        guess_limit -= 1
        print("Wrong guess, try a smaller number.")
        print("Remaining guesses:", guess_limit)
    elif guess < generated_number:
        guess_limit -= 1
        print("Wrong guess, try a bigger number.")
        print("Remaining guesses:", guess_limit)

    if guess_limit == 0:
        print(
            "You have no guesses left.",
            "The number generated by the computer was:",
            generated_number
        )
        break
